### ISSUE TITLE
Expected [object Object] to be a GraphQL schema

### ISSUE THREAD

**Issue by ziedHamdi** [graphql-compose/graphql-compose-mongoose#103]
I'm new to graphql-compose

I'm trying to launch a first service on a simple mongoose schema:

graphql.js :

```
import mongoose from 'mongoose'
import { composeWithMongoose} from 'graphql-compose-mongoose'
import { schemaComposer } from 'graphql-compose'

const db = require( '../models/db' )
//const mongoose = require('mongoose');
const folderDAO = mongoose.model('folder');

const customizationOptions = {}; // left it empty for simplicity, described below
const folderTC = composeWithMongoose(folderDAO, customizationOptions);

schemaComposer.rootQuery().addFields({
    folderOne: folderTC.getResolver('findOne'),
})

const graphqlSchema = schemaComposer.buildSchema()

console.log("Schema built : ", graphqlSchema )

export default graphqlSchema
```
Now in my server code, I have this:

```
const express = require('express');
const graphqlHTTP = require('express-graphql')
const GraphQLSchema = require('./app_api/routes/graphql')
    app.use('/graphql', graphqlHTTP({
        schema: GraphQLSchema,
        graphiql: true,
        formatError: error => ({
            message: error.message,
            locations: error.locations,
            stack: error.stack ? error.stack.split('\n') : [],
            path: error.path
        })
    }));
```
On graphiql, when I attempt the following query:

```
{
  folderOne(filter: {}, sort: _ID_ASC) {
    name
  }
}
```
I get the following error:

```
{
  "errors": [
    {
      "message": "Expected [object Object] to be a GraphQL schema.",
      "stack": [
        "Error: Expected [object Object] to be a GraphQL schema.",
        "    at invariant (/Users/zied/work/share_place/node_modules/graphql/jsutils/invariant.js:19:11)",
        "    at validateSchema (/Users/zied/work/share_place/node_modules/graphql/type/validate.js:55:60)",
        "    at assertValidSchema (/Users/zied/work/share_place/node_modules/graphql/type/validate.js:80:16)",
        "    at validate (/Users/zied/work/share_place/node_modules/graphql/validation/validate.js:58:35)",
        "    at /Users/zied/work/share_place/node_modules/express-graphql/dist/index.js:139:52",
        "    at <anonymous>",
        "    at process._tickDomainCallback (internal/process/next_tick.js:228:7)"
      ]
    }
  ]
}
```
What could I be missing??? I think this is an issue with the lib or the doc since I reproduced exactly what you do in your doc

p.s: this question is on sf, but since no one answered, I copied it here
[https://stackoverflow.com/questions/50607329/graphql-compose-mongoose-generating-an-error-expected-object-object-to-be-a-g](https://stackoverflow.com/questions/50607329/graphql-compose-mongoose-generating-an-error-expected-object-object-to-be-a-g)

**Comment by nodkz** [comment]
It looks like 
```js
const GraphQLSchema = require('./app_api/routes/graphql')
```
is empty. Maybe wrong import or something else.

For graphqlHTTP you should provide correct `schema` property:
```js
    const graphqlSchema = schemaComposer.buildSchema()
    app.use('/graphql', graphqlHTTP({
        schema: graphqlSchema, // <-------------
        graphiql: true,
        formatError: error => ({
            message: error.message,
            locations: error.locations,
            stack: error.stack ? error.stack.split('\n') : [],
            path: error.path
        })
    }));
```

**Comment by ziedHamdi** [comment]
This is what I have when I log graphqlSchema to the console

```
{ default: 
   GraphQLSchema {
     __allowedLegacyNames: undefined,
     _queryType: Query,
     _mutationType: undefined,
     _subscriptionType: undefined,
     _directives: [ [Object], [Object], [Object] ],
     astNode: undefined,
     _typeMap: 
      { Query: Query,
        FilterFindOnefolderInput: FilterFindOnefolderInput,
        String: String,
        folderCreationInfoInput: folderCreationInfoInput,
        FolderfolderTreeIdsPerNamesInput: FolderfolderTreeIdsPerNamesInput,
        MongoID: MongoID,
        EnumfolderFolderType: EnumfolderFolderType,
        OperatorsFilterFindOnefolderInput: OperatorsFilterFindOnefolderInput,
        _idOperatorsFilterFindOnefolderInput: _idOperatorsFilterFindOnefolderInput,
        Int: Int,
        SortFindOnefolderInput: SortFindOnefolderInput,
        folder: folder,
        folderCreationInfo: folderCreationInfo,
        folderTreeIdsPerNames: folderTreeIdsPerNames,
        __Schema: __Schema,
        __Type: __Type,
        __TypeKind: __TypeKind,
        Boolean: Boolean,
        __Field: __Field,
        __InputValue: __InputValue,
        __EnumValue: __EnumValue,
        __Directive: __Directive,
        __DirectiveLocation: __DirectiveLocation },
     _implementations: {} } }
```

**Comment by nodkz** [comment]
When you use `require()` for import and export something as `export default`.
Then you need to use such form `require(...).default`.

```js
const schema = require('./app_api/routes/graphql').default;
```

**Comment by ziedHamdi** [comment]
Ok!!!

Sorry Nodkz, I'm new to these syntaxes. Thanks a lot for your help. Can you please consider adding the tag graphql-compose and graphql-compose-mongoose to stackoverflow so poeple will avoid posting their issues here before ensuring it's a bug?

**Comment by NamishM** [comment]
> It looks like
> 
> ```js
> const GraphQLSchema = require('./app_api/routes/graphql')
> ```
> 
> is empty. Maybe wrong import or something else.
> 
> For graphqlHTTP you should provide correct `schema` property:
> 
> ```js
>     const graphqlSchema = schemaComposer.buildSchema()
>     app.use('/graphql', graphqlHTTP({
>         schema: graphqlSchema, // <-------------
>         graphiql: true,
>         formatError: error => ({
>             message: error.message,
>             locations: error.locations,
>             stack: error.stack ? error.stack.split('\n') : [],
>             path: error.path
>         })
>     }));
> ```

yea, only when there is problem in import/export with schema object, the above mentioned issue will arise.

**Comment by sundarkandasamy** [comment]
Thank you, nodkz. 
`const schema = require('./app_api/routes/graphql').default;`
solves my error
