### ISSUE TITLE
How to connect built schema to Apollo Server?

### ISSUE THREAD

**Issue by Toreilly317** [graphql-compose/graphql-compose-mongoose#138]
I am looking to figure out the correct way to pass my graphql schema generated by `schemaComposer.buildSchema()` to Apollo server
```

**models/user.js**
import mongoose from 'mongoose';
import { composeWithMongoose } from 'graphql-compose-mongoose';
import { schemaComposer } from 'graphql-compose';


const UserSchema = new mongoose.Schema({
  firstName: String,
  lastName: String,
  pasword: String,
}, {
    timestamps: true
  })

const User = mongoose.model('User', UserSchema);
const customizationOptions = {}
const UserTC = composeWithMongoose(User, customizationOptions);

schemaComposer.Query.addFields({
  userById: UserTC.getResolver('findById'),
  userByIds: UserTC.getResolver('findByIds'),
  userOne: UserTC.getResolver('findOne'),
});

schemaComposer.Mutation.addFields({
  userCreateOne: UserTC.getResolver('createOne'),
  userUpdateById: UserTC.getResolver('updateById'),
  userUpdateOne: UserTC.getResolver('updateOne'),
});

export default schemaComposer.buildSchema()
```
**server.js**
```
import { ApolloServer } from 'apollo-server';
import schema from "./models/User"
import mongoose from 'mongoose'
import { MONGO_URI } from './config/keys'

mongoose.connect(MONGO_URI, { useNewUrlParser: true })
  .then(() => console.log('DB connected'))

const server = new ApolloServer(schema);

server.listen().then(({ url }) => {
  console.log(`🚀  Server ready at ${url}`);
});
```
**but when I run the file i am getting this error**
```
Error: Apollo Server requires either an existing schema or typeDefs
    at new ApolloServerBase (file:///home/to/Desktop/local/node_modules/apollo-server-core/dist/ApolloServer.js:119:23)
    at new ApolloServer (file:///home/to/Desktop/local/node_modules/apollo-server-express/dist/ApolloServer.js:44:1)
    at new ApolloServer (file:///home/to/Desktop/local/node_modules/apollo-server/dist/index.js:23:9)
    at Object.<anonymous> (file:///home/to/Desktop/local/index.js:22:16)
    at Generator.next (<anonymous>)

```

**Comment by Toreilly317** [comment]
Figured it out by changing 

```export default schemaComposer.buildSchema()```

to 
```
const schema = schemaComposer.buildSchema()
export default { schema }
```
