### ISSUE TITLE
Discriminator type issues

### ISSUE THREAD

**Issue by bloodhawk** [graphql-compose/graphql-compose-mongoose#166]
As of right now, the base interface returned creates types rather than interfaces for nested objects. Due to this, there is no way to do things like https://graphql.github.io/graphql-spec/June2018/#example-5cc55

Was this the intention?

**Comment by nodkz** [comment]
Can you provide a real example where it can be tested?

Nested interfaces should work and if not then it's a bug.

**Comment by bloodhawk** [comment]
Hi @nodkz thanks for getting back to me. I added a failing example to https://github.com/bloodhawk/graphql-compose-examples

I then went to http://localhost:3000/mongooseDiscriminators-playground and tried to run:

```
query {
  characterById(_id: "hi") {
  	aNestedField {
      anotherGenericNestedField
    	...on Droid {
        aDroidNestedField
      }
    }
  }
}
```
and was greeted with the error:

```
{
  "error": {
    "errors": [
      {
        "message": "Fragment cannot be spread here as objects of type \"CharacterANestedField\" can never be of type \"Droid\".",
        "stack": [
          "Fragment cannot be spread here as objects of type \"CharacterANestedField\" can never be of type \"Droid\".",
          "",
          "GraphQL request (5:7)",
          "4:       anotherGenericNestedField",
          "5:       ... on Droid {",
          "         ^",
          "6:         aDroidNestedField",
          "",
          "    at Object.InlineFragment (/Users/aaronrumery/Documents/testing/graphql-compose-examples/node_modules/graphql/validation/rules/PossibleFragmentSpreads.js:53:29)",
          "    at Object.enter (/Users/aaronrumery/Documents/testing/graphql-compose-examples/node_modules/graphql/language/visitor.js:334:29)",
          "    at Object.enter (/Users/aaronrumery/Documents/testing/graphql-compose-examples/node_modules/graphql/language/visitor.js:385:25)",
          "    at visit (/Users/aaronrumery/Documents/testing/graphql-compose-examples/node_modules/graphql/language/visitor.js:252:26)",
          "    at validate (/Users/aaronrumery/Documents/testing/graphql-compose-examples/node_modules/graphql/validation/validate.js:63:22)",
          "    at /Users/aaronrumery/Documents/testing/graphql-compose-examples/node_modules/express-graphql/dist/index.js:154:52",
          "    at process._tickCallback (internal/process/next_tick.js:68:7)"
        ]
      },...
```

**Comment by bloodhawk** [comment]
Here is an example:

```
type Book implements Searchable {
  searchPreviewText: String!
  author: String!
  nestedField: BookNestedField
}

type BookNestedField implements someCommonNestedInterface {
  a: String
  d: String
}

type Movie implements Searchable {
  searchPreviewText: String!
  directory: String!
  nestedField: MovieNestedField
}

type MovieNestedField implements someCommonNestedInterface {
  a: String
  c: String
}

type Query {
  search(text: String!): [Searchable]!
}

interface Searchable {
  searchPreviewText: String!
  nestedField: someCommonNestedInterface
}

interface someCommonNestedInterface {
  a: String
}

type User implements Searchable {
  searchPreviewText: String!
  username: String!
  nestedField: UserNestedField
}

type UserNestedField implements someCommonNestedInterface {
  a: String
  b: String
}
```

with query

```
query {
  search(text: "hi") {
    searchPreviewText
    ...on Book {
      nestedField {
        d
      }
    }
    nestedField {
      a
    }
  }
}
```
