### ISSUE TITLE
Mongoose pagination resolver throws an error on startup First arg for prepareConnectionResolver() should be instance of ObjectTypeComposer

### ISSUE THREAD

**Issue by ziedHamdi** [graphql-compose/graphql-compose-mongoose#168]
Hi 

Please notice this can be an issue of compatibility of modules this is the relevant part of my package.json
```
    "graphql": "^0.13.2",
    "graphql-compose": "^5.10.4",
    "graphql-compose-connection": "^4.0.0",
    "graphql-compose-mongoose": "^5.3.1",
```

I have this entity declaration

graphql/Complaint.js
```
import {composeWithMongoose} from 'graphql-compose-mongoose';
import {schemaComposer} from 'graphql-compose';

import {Complaint, ComplaintAction, ComplaintAttachment, Entity, EntityGroup} from '../db'
import composeWithConnection from "graphql-compose-connection";
import {updateEntityIssuesCount} from "../business/entityProcessor";
import {updateGroupIssuesCount} from "../business/entityGroupProcessor";
import {findOrderForNewComplaint} from "../business/orderProcessor";

const customizationOptions = {}; // left it empty for simplicity, described below
const ComplaintTC = composeWithMongoose(Complaint, customizationOptions) //this is line 11

const addTitleRegexSearch = function (resolverName) {
	const extendedResolver = ComplaintTC.getResolver(resolverName).addFilterArg({
		name: 'titleRegexp',
		type: 'String',
		description: 'Search by title in regExp',
		query: (query, value, resolveParams) => { // eslint-disable-line
			query.title = new RegExp(value, 'i'); // eslint-disable-line
		},
	});
	extendedResolver.name = resolverName;
	ComplaintTC.addResolver(extendedResolver);
}

const addByUserIdSearch = function (resolverName) {
	const extendedResolver = ComplaintTC.getResolver(resolverName).addFilterArg({
		name: 'userId',
		type: 'String',
		description: 'Search by user id',
		query: (query, value, resolveParams) => { // eslint-disable-line
			query["user.userId"] = value; // eslint-disable-line
		},
	});
	extendedResolver.name = resolverName;
	ComplaintTC.addResolver(extendedResolver);
}

const addByEntityGroupIdSearch = function (resolverName) {
	const extendedResolver = ComplaintTC.getResolver(resolverName).addFilterArg({
		name: 'egId',
		type: 'String',
		description: 'Search by entity group id',
		query: (query, value, resolveParams) => { // eslint-disable-line
			//db.getCollection('complaints').find({"entity.groupTree":{$elemMatch: {"name":"Zied"}}})
			query["entity.groupTree"] = {$elemMatch: {id: value}}; // eslint-disable-line
		},
	});
	extendedResolver.name = resolverName;
	ComplaintTC.addResolver(extendedResolver);
}

const addByKindSearch = function (resolverName) {
	const extendedResolver = ComplaintTC.getResolver(resolverName).addFilterArg({
		name: 'kind',
		type: 'String',
		description: 'Search by kind',
		query: (query, value, resolveParams) => { // eslint-disable-line
			query["entity.kind"] = value; // eslint-disable-line
		},
	});
	extendedResolver.name = resolverName;
	ComplaintTC.addResolver(extendedResolver);
}

/**
 * Adds visibility of issues against logged profile
 * @param resolverName
 */
const addViewerSearchConstraint = function (resolverName) {
	const extendedResolver = ComplaintTC.getResolver(resolverName).addFilterArg({
		name: 'viewer',
		type: 'String',
		description: 'Search by title in regExp',
		query: (query, value, rp) => { // eslint-disable-line
			if (value == 'USER') {
				const user = rp.context.user;
				if (user != null) query['$or'] = [{public: true}, {'user.userId': user.id}] // eslint-disable-line
				else query.public = true
			} else if (value == 'SAS_AGENT') {
				//TODO check if the connected user has a SAS role in this entity_group
			}
		},
	});
	extendedResolver.name = resolverName;
	ComplaintTC.addResolver(extendedResolver);
}

const addDelayExpiredSearchConstraint = function (resolverName) {
	const extendedResolver = ComplaintTC.getResolver(resolverName).addFilterArg({
		name: 'delayExpired',
		type: 'Boolean',
		description: 'Search by title in regExp',
		query: (query, value, rp) => { // eslint-disable-line
			if (value == null) return

			query.public = value
		},
	});
	extendedResolver.name = resolverName;
	ComplaintTC.addResolver(extendedResolver);
};

const addInteractionStateSearchConstraint = function (resolverName) {
	const extendedResolver = ComplaintTC.getResolver(resolverName).addFilterArg({
		name: 'interactionStateList',
		type: '[EnumComplaintInteractionState]',
		description: 'Search by interaction state',
		query: (query, value, resolveParams) => { // eslint-disable-line
			//FIXME should check for user read access
			// if (resolveParams.context.user != null) {
			if (value == null || value.length == 0) {
				return
			} else if (value.length == 1) {
				query.interactionState = value[0]
			} else {
				const interactionStateValues = []
				for (let i = 0; i < value.length; i++) {
					interactionStateValues.push({interactionState: value[i]})
				}
				query['$or'] = interactionStateValues // eslint-disable-line
			}
			// } else {
			// 	//
			// }
		},
	});
	extendedResolver.name = resolverName;
	ComplaintTC.addResolver(extendedResolver);
}

const addInteractionSpecifierSearchConstraint = function (resolverName) {
	const extendedResolver = ComplaintTC.getResolver(resolverName).addFilterArg({
		name: 'interactionSpecifierList',
		type: '[EnumComplaintInteractionSpecifier]',
		description: 'Search by interaction specifier',
		query: (query, value, resolveParams) => { // eslint-disable-line
			//FIXME should check for user read access
			// if (resolveParams.context.user != null) {
			if (value == null || value.length == 0) {
				return
			} else if (value.length == 1) {
				query.interactionSpecifier = value[0]
			} else {
				const interactionStateValues = []
				for (let i = 0; i < value.length; i++) {
					interactionStateValues.push({interactionSpecifier: value[i]})
				}
				query['$or'] = interactionStateValues // eslint-disable-line
			}
			// } else {
			// 	//
			// }
		},
	});
	extendedResolver.name = resolverName;
	ComplaintTC.addResolver(extendedResolver);
};


addByKindSearch('findMany')
addByUserIdSearch('findMany')
addTitleRegexSearch('findMany')
addByEntityGroupIdSearch('findMany')
addViewerSearchConstraint('findMany')
addDelayExpiredSearchConstraint('findMany')
addInteractionStateSearchConstraint('findMany')
addInteractionSpecifierSearchConstraint('findMany')

addByKindSearch('connection')
addByUserIdSearch('connection')
addTitleRegexSearch('connection')
addByEntityGroupIdSearch('connection')
addViewerSearchConstraint('connection')
addDelayExpiredSearchConstraint('connection')
addInteractionStateSearchConstraint('connection')
addInteractionSpecifierSearchConstraint('connection')

ComplaintTC.addFields({
	isLiking: { // extended
		type: 'Boolean', // String, Int, Float, Boolean, ID, Json
		description: 'queries db if the connecteduser has liked this complaint',
		resolve: async (source, args, context, info) => {
			const connectedUser = context.user
			if( connectedUser == null )
				return false
			const action = await ComplaintAction.findOne({complaintId:source._id, "user.userId":connectedUser.id, actionType:"USER_LIKE"})
			return action != null
		},
	},
	hasSimilarIssue: { // extended
		type: 'Boolean', // String, Int, Float, Boolean, ID, Json
		description: 'queries db if the connecteduser has liked this complaint',
		resolve: async (source, args, context, info) => {
			const connectedUser = context.user
			if( connectedUser == null )
				return false
			const action = await ComplaintAction.findOne({complaintId:source._id, "user.userId":connectedUser.id, actionType:"SAME_ISSUE"})
			return action != null
		},
	}
})

schemaComposer.rootQuery().addFields({
	complaintById: ComplaintTC.getResolver('findById'),
	complaintByIds: ComplaintTC.getResolver('findByIds'),
	complaintOne: ComplaintTC.getResolver('findOne'),
	complaintMany: ComplaintTC.getResolver('findMany'),
	complaintCount: ComplaintTC.getResolver('count'),
	complaintConnection: ComplaintTC.getResolver('connection')
});


const complaintCreateOne = ComplaintTC.getResolver('createOne');
complaintCreateOne.getArgTC('record').makeOptional(['entityGroupId', 'user', 'state', 'interactionState']);
schemaComposer.rootMutation().addFields({
	// complaintUpdateOne: new Resolver({
	// 	name: complaintUpdateOneResolver.name,
	// 	displayName: complaintUpdateOneResolver.displayName,
	// 	kind: complaintUpdateOneResolver.kind,
	// 	type: complaintUpdateOneResolver.type,
	// 	args: [...complaintUpdateOneResolver.args, {'attachmentsToRemove': ['String']}],
	// 	resolve: async (params) => {
	// 		console.log("args of complaintUpdateOne: ", complaintUpdateOneResolver.args)
	// 		complaintUpdateOneResolver.resolve(params)
	// 		const {args, context} = params;
	// 		// do some other job here: remove attachment files from storage
	// 	}
	// }),
	complaintCreate: complaintCreateOne.wrapResolve(next => async rp => {
		const {user} = rp.context
		if (!user) throw new Error("IllegalState: no user connected, this method should not be called")

		const entityId = rp.args.record.entityId
		const entity = await Entity.findOne({_id:entityId});
		const entityGroup = await EntityGroup.findOne({_id:entity.entityGroupId});

		rp.args.record['user'] = {
			userId: user.id,
			userName: user.name,
			roleInShop: "ASA"
		}
		rp.args.record['state'] = "DRAFT"
		rp.args.record['unanswered'] = true
		rp.args.record['entityGroupId'] = entity.entityGroupId
		rp.args.record['entity'] = {
			name: entity.name,
			kind: entity.kind,
			groupTree: [{
				id: entityGroup._id,
				name: entityGroup.name
			}]
		}
		rp.args.record['issueRef'] = await Complaint.count({entityGroupId:entityGroup._id})
		const resolverResult = next(rp);

		return resolverResult
	}),
	complaintUpdateOne: ComplaintTC.getResolver('updateOne').wrapResolve(next => async rp => {
		console.log(" removed attachments unused : ", rp.args.record.removedAttachments)
		const complaint = await Complaint.findById(rp.args.record._id)
		const entity = await updateEntityIssuesCount(complaint.entityId);
		const entityGroup = await updateGroupIssuesCount(entity);

		return next(rp)
	}),
	complaintUpdateById: ComplaintTC.getResolver('updateById').wrapResolve(next => async rp => {
		rp.args.record['state'] = "OPEN"

		const complaint = await Complaint.findById(rp.args.record._id)

		const order = await findOrderForNewComplaint(complaint.entityGroupId)
		rp.args.record['public'] = (order == null)
		rp.args.record['orderId'] = (order == null) ? null : order._id

		const removedAttachments = rp.args.record.removedAttachments;
		if (removedAttachments && removedAttachments.length > 0) {
			for (let i = 0; i < removedAttachments.length; i++) {
				const attachmentId = removedAttachments[i].attachmentId;
				if (attachmentId != null)
					await ComplaintAttachment.deleteOne({_id: attachmentId})
				else
					console.log("no Id for attachment to remove: ", removedAttachments[i])
			}
			rp.args.record.removedAttachments = []
		}

		const resolverResult = next(rp);
		const entity = await updateEntityIssuesCount(complaint.entityId);
		await updateGroupIssuesCount(entity);
		return resolverResult
	}),
	complaintUpdateMany: ComplaintTC.getResolver('updateMany'),
	complaintRemoveById: ComplaintTC.getResolver('removeById'),
	complaintRemoveOne: ComplaintTC.getResolver('removeOne'),
	complaintRemoveMany: ComplaintTC.getResolver('removeMany'),
});

composeWithConnection(ComplaintTC, {
	findResolverName: 'findMany',
	countResolverName: 'count',
	sort: {
		_ID_ASC: {
			value: {_id: 1},
			cursorFields: ['_id'],
			beforeCursorQuery: (rawQuery, cursorData, resolveParams) => {
				if (!rawQuery._id) rawQuery._id = {};
				rawQuery._id.$lt = cursorData._id;
			},
			afterCursorQuery: (rawQuery, cursorData, resolveParams) => {
				if (!rawQuery._id) rawQuery._id = {};
				rawQuery._id.$gt = cursorData._id;
			},
		},

		CREATED_ASC: {
			value: {createdAt: 1},
			cursorFields: ['createdAt'],
			beforeCursorQuery: (rawQuery, cursorData, resolveParams) => {
				if (!rawQuery.createdAt) rawQuery.createdAt = {};
				rawQuery.createdAt.$lt = cursorData.createdAt;
			},
			afterCursorQuery: (rawQuery, cursorData, resolveParams) => {
				if (!rawQuery.createdAt) rawQuery.createdAt = {};
				rawQuery.createdAt.$gt = cursorData.createdAt;
			},
		},

		_ID_DESC: {
			value: {_id: -1},
			cursorFields: ['_id'],
			beforeCursorQuery: (rawQuery, cursorData, resolveParams) => {
				if (!rawQuery._id) rawQuery._id = {};
				rawQuery._id.$gt = cursorData._id;
			},
			afterCursorQuery: (rawQuery, cursorData, resolveParams) => {
				if (!rawQuery._id) rawQuery._id = {};
				rawQuery._id.$lt = cursorData._id;
			},
		}
	}
})

// const complaintUpdateOneResolver = ComplaintTC.getResolver('updateOne');

// const removedAttachmentsITC = schemaComposer.getITC('ComplaintComplaintAttachmentsInput').clone('ComplaintComplaintRemovedAttachmentsInput ');

// console.log( "###### updateOneInputITC type:", ComplaintTC.getResolver('updateOne') )
// const updateOneInputITC = ComplaintTC.getResolver('updateOne').getArgTC('record');
// console.log( "###### attachments type:", updateOneInputITC.getFieldType("attachments") )
// updateOneInputITC.addFields({
// 	newFields: [{
// 		removedAttachmentList: { // standard GraphQL like field definition
// 			type: updateOneInputITC.getFieldTC("attachments").clone('ComplaintComplaintRemovedAttachmentListInput').getType(),
// 			resolve: (source) => {console.log( "removedAttachments source value: ", source ); return null},
// 		},
// 	}]
// });

export default schemaComposer;
```

For some reason, I changed it without pointing to the good file, so I thought everything was working fine, but today I pointed to the correct file and I have this error (I added some logging to understand what's going on behind the scene). Please notice this happens with the very first entity, it might be caused by versions incompatibility (I'm on a new machine and just did an npm i)

creating resolver for  TypeComposer { gqType: Complaint } :  findById
creating resolver for  TypeComposer { gqType: Complaint } :  findByIds
creating resolver for  TypeComposer { gqType: Complaint } :  findOne
creating resolver for  TypeComposer { gqType: Complaint } :  findMany
creating resolver for  TypeComposer { gqType: Complaint } :  updateById
creating resolver for  TypeComposer { gqType: Complaint } :  updateOne
creating resolver for  TypeComposer { gqType: Complaint } :  updateMany
creating resolver for  TypeComposer { gqType: Complaint } :  removeById
creating resolver for  TypeComposer { gqType: Complaint } :  removeOne
creating resolver for  TypeComposer { gqType: Complaint } :  removeMany
creating resolver for  TypeComposer { gqType: Complaint } :  createOne
creating resolver for  TypeComposer { gqType: Complaint } :  createMany
creating resolver for  TypeComposer { gqType: Complaint } :  count
creating resolver for  TypeComposer { gqType: Complaint } :  pagination
```
D:\work\weally\server\node_modules\graphql-compose-mongoose\node_modules\graphql-compose-pagination\lib\paginationResolver.js:26
    throw new Error('First arg for prepareConnectionResolver() should be instance of ObjectTypeComposer, found '+tc.constructor.name+ ' : '+ JSON.stringify(tc));
    ^

Error: First arg for prepareConnectionResolver() should be instance of ObjectTypeComposer, found TypeComposer : {"gqType":"Complaint"}
    at preparePaginationResolver (D:\work\weally\server\node_modules\graphql-compose-mongoose\node_modules\graphql-compose-pagination\lib\paginationResolver.js:26:11)
    at pagination (D:\work\weally\server\node_modules\graphql-compose-mongoose\lib\resolvers\pagination.js:26:20)
    at names.forEach.resolverName (D:\work\weally\server\node_modules\graphql-compose-mongoose\lib\composeWithMongoose.js:103:26)
    at Array.forEach (<anonymous>)
    at createResolvers (D:\work\weally\server\node_modules\graphql-compose-mongoose\lib\composeWithMongoose.js:97:9)
    at composeWithMongoose (D:\work\weally\server\node_modules\graphql-compose-mongoose\lib\composeWithMongoose.js:44:5)
    at Object.<anonymous> (D:/work/weally/server/graphql/complaint.js:11:21)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at loader (D:\work\weally\server\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\work\weally\server\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:/work/weally/server/graphql/index.js:1:1)
```

Here's the declaration of Complaint in db.js

```
import mongoose, {Schema} from 'mongoose';
import UserInfoSchema from './fragment/userInfoFragment'
import {Actions} from "../procedures";

const GroupTreeItem = new Schema({
	id:{type: String, required: true},
	name:{type: String, required: true},
})


const ComplainSchema = new Schema({
	entityGroupId: {type: String, required: true},
	entityId: {type: String, required: true},
	entity: {
		name:{type: String, required: true},
		kind:{type:String, enum:["AS", "PRODUCT"], required: true},
		groupTree: [GroupTreeItem],
	},
	orderId : String,
	billingDate: {type:Date, default: new Date()},
	issueDate: {type:Date, default: new Date()},
	issueRef: {type:String},
	solvedDate: {type:Date},
	user: {type: UserInfoSchema, required: true, index: true},
	title: {type:String, default:""}, // standard types
	desc: {type:String, default:""},
	state: {required: true, type: String, enum: ["DRAFT", "OPEN", "SOLVED", "REFUSED", "CONFLICT"]},
	interactionState: {required: true, type: String, enum: [Actions.SHOP_ACTION_EXPECTED, Actions.SHOP_ACTION_REFUSED, Actions.USER_ACTION_EXPECTED, Actions.USER_ACTION_REFUSED, Actions.USER_SATISFIED], default:Actions.SHOP_ACTION_EXPECTED},
	interactionSpecifier: {type: String, enum: ["INFO", "PAYMENT", "REPLACEMENT"]},
	/**if the entity is of type "service" and is a paying member, the public variable will be false for a week before moving to a visible state.
	 * The non public state makes the issue visible only for its creator and the related entity members so they can communicate about it and find a solution. The state remains open for all the negociation, the stateNegocation explais who should do the next action
	 * The OPEN, REFUSED and CONFLICT states are considered as open issues, issues with other states are visible only to restricted viewers
	 */
	public: {type: Boolean, default: true},
	mainAttachmentIndex:{type:Number, default:0},
	likesCount:{type:Number, default:0},
	similarIssuesCount:{type:Number, default:0},
	popularity:{type:Number, default:1}, // this value is computed

	attachments: [{
		url: {type: String, required: true},
		thumbUrl: {type: String, required: true},
		name: String,
		mimeType: String,
		/**
		 * The attachmentId is used when the attachment is stored as a blob in mongodb
		 */
		attachmentId: Schema.Types.ObjectId
	}],
	removedAttachments: [{
		url: {type: String, required: true},
		thumbUrl: {type: String, required: true},
		name: String,
		mimeType: String,
		/**
		 * The attachmentId is used when the attachment is stored as a blob in mongodb
		 */
		attachmentId: Schema.Types.ObjectId
	}],

	/**
	 * this field is used by the entity owner to see if he has answered to the user: as long as he didn't answer this field is visually marked as "unanswered"
	 */
	unanswered: {type: Boolean, default:true, index: true},
	createdAt: {type: Date, index: true},
	updatedAt: {type: Date, index: true},

}, {timestamps: {}})

mongoose.connection.collection('complaints').createIndex({
	entityId: 1,
	popularity: 1
})

export default mongoose.model('Complaint', ComplainSchema)

```

I think we need a verbose resolving option to see what's going on inside, for me, if composeWithMongoose.js:44:5 accepts my arguments, I shouldn't have to go to the internals : especially that all resolvers were accepted (see the list above), but not pagination.

And something also weired, is that I didn't ask for many of these generated resolvers, I'm surprised they get generated. Doesn't this impact performance?

Best regards, 
Sorry, the code is big, but since the error could be anywhere in it, I didn't know how to simplify it

**Comment by ziedHamdi** [comment]
Please notice that when I attempted to migrate to the newest versions I have issues with my declarations:

my new package.json
```
    "graphql-compose": "^6.3.1",
    "graphql-compose-connection": "^5.0.0",
    "graphql-compose-mongoose": "^6.1.0",
```

Throws an error for my declarations : 
```
D:\work\weally\server\node_modules\graphql-compose\lib\Resolver.js:51
      throw new Error('You must provide SchemaComposer instance as a second argument for `new Resolver(opts, SchemaComposer)`');
      ^

Error: You must provide SchemaComposer instance as a second argument for `new Resolver(opts, SchemaComposer)`
    at new Resolver (D:\work\weally\server\node_modules\graphql-compose\lib\Resolver.js:51:13)
    at Object.<anonymous> (D:/work/weally/server/graphql/complaintAction.js:40:31)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at loader (D:\work\weally\server\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\work\weally\server\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:/work/weally/server/graphql/index.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at loader (D:\work\weally\server\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\work\weally\server\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
```

Since i'm declaring my resolver this way:
```
const complaintActionToggle = new Resolver({
	name: 'complaintActionToggle',
	type: createOneResolver.type,
	args: {
		complaintId: 'String!',
		actionType: 'EnumComplaintActionActionType!',
		value: 'String!'
	},
	resolve: async ({source, args, context, info}) => {//...
   }
```

**Comment by ziedHamdi** [comment]
Ok,

When I did migrate to the newest version and updated my code accordingly, thigs are working fine again
