### ISSUE TITLE
addRelation with different TCs cause input Filter error

### ISSUE THREAD

**Issue by ChrisPei** [graphql-compose/graphql-compose-mongoose#233]
I have twoTCs:

```
const PaymentWalletSchema = new mongoose.Schema({
  ...
  uid: Number,
  ...
});

const PaymentWalletTC = composeWithMongoose(PaymentWallet, {});
```

```
const UserSchema = new mongoose.Schema({
  ...
  _id: Number,
  ...
});

const UserTC = composeWithMongoose(UserSchema , {});
```

without addRelation, everything is fine.

but now addRelation:

```
PaymentWalletTC.addRelation('user', {
  resolver: () => UserTC.getResolver('findById'),
  prepareArgs: {
    _id: source => {
      return source['uid'];
    }
  },
  projection: { uid: 1 }
});
```

do GraphQL Query:

```
query {
  PaymentWalletOne(filter: { uid: 189 }) {
    value
  }
}
```

got error message:

```
{
  "errors": [
    {
      "message": "Unexpected error value: [{ message: \"Unknown type \\\"FilterFindOnePaymentWalletInput\\\". Did you mean \\\"FilterFindOneUserInput\\\", \\\"FilterFindManyUserInput\\\", \\\"FilterUpdateManyUserInput\\\", or \\\"FilterRemoveManyUserInput\\\"?\", locations: [] }]",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "PaymentWalletOne"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Unexpected error value: [{ message: \"Unknown type \\\"FilterFindOnePaymentWalletInput\\\". Did you mean \\\"FilterFindOneUserInput\\\", \\\"FilterFindManyUserInput\\\", \\\"FilterUpdateManyUserInput\\\", or \\\"FilterRemoveManyUserInput\\\"?\", locations: [] }]",
            "    at asErrorInstance (C:\\...\\node_modules\\graphql\\execution\\execute.js:481:10)",
            "    at process._tickCallback (internal/process/next_tick.js:68:7)"
          ]
        }
      }
    }
  ],
  "data": {
    "PaymentWalletOne": null
  }
}
```

so, how to resolve it? 
seems PaymentWalletTC use UserTC cause this issues.

**Comment by ChrisPei** [comment]
well, I made a stupid mistake.
I built schema and use it two times.
